### PR TITLE
Update to CC 1.0 to satisfy previous license requirements

### PR DESCRIPTION
**Pull request by million1156**
catto or whatever uploaded 1.0 to his repo, and technically that means we have to link the license :P

### CODE REVIEW

**Comment by ZEROPOINTBRUH** [comment]
Not necessary, his request was already fulfilled and finalized.

**Comment by ZEROPOINTBRUH** [comment]
To addon to it
```
devgui_cmd "Game Settings/Lobby/Credits:1/Sku-111/Max Players Limit Bypass" " "
Credits:1/Sku-111
```
The code isn't his to begin with, its a modification of sku's code from pastebin
Therefor he is not liable of holding the license:

**Comment by ZEROPOINTBRUH** [comment]
However to follow up on the request, the license was changed to allow anyone to modify it or make use of it.

**Comment by ZEROPOINTBRUH** [comment]
https://github.com/ProjectDonetsk/Project-Donetsk-DevMenu/commit/389618274c4f8d7efa70d229962388bcb3e8f4f8

**Comment by million1156** [comment]
> To addon to it
> 
> ```
> 
> devgui_cmd "Game Settings/Lobby/Credits:1/Sku-111/Max Players Limit Bypass" " "
> 
> Credits:1/Sku-111
> 
> ```
> 
> The code isn't his to begin with, its a modification of sku's code from pastebin
> 
> Therefor he is not liable of holding the license:

LMAOOOOO 😂

**Pull request closed without merging**
